// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nuhnjuitrpuiizvxljdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im51aG5qdWl0cnB1aWl6dnhsamRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDExODksImV4cCI6MjA3MTY3NzE4OX0.g_Vi4LBiM2JyI8JqfbuGFQtQf-kf9YUnFOOCyv0YLLQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});